### ISSUE TITLE
Almost all the preview images are dead

### ISSUE THREAD

**Issue by nyngwang** [harrisoncramer/harrisoncramer.me#81]
Hi, sorry for being annoying, but you said that

> Please make a pull request if you want to fix a bug or suggest a feature. The [repository ](https://github.com/harrisoncramer/harrisoncramer.me)is on Github.

I cannot help with debugging, but here is a report.

![image](https://user-images.githubusercontent.com/24765272/236997823-edd142bc-21ce-40a1-8a93-0decaaea1537.png)

**Comment by harrisoncramer** [comment]
Hey sorry for the delayed response here. I'm guessing this is some sort of latency issue with your network, these are the previews that you will see when the image itself is loading.

Haven't been able to replicate this, so going to close out.
